//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKÜTÜPHANE.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKütüphaneEntities : DbContext
    {
        public DBKütüphaneEntities()
            : base("name=DBKütüphaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Ceza> Tbl_Ceza { get; set; }
        public virtual DbSet<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual DbSet<Tbl_Kasa> Tbl_Kasa { get; set; }
        public virtual DbSet<Tbl_Kitap> Tbl_Kitap { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_Üye> Tbl_Üye { get; set; }
        public virtual DbSet<Tbl_Yazar> Tbl_Yazar { get; set; }
        public virtual DbSet<Tbl_Hakkımızda> Tbl_Hakkımızda { get; set; }
        public virtual DbSet<Tbl_Abone> Tbl_Abone { get; set; }
        public virtual DbSet<Tbl_İletişim> Tbl_İletişim { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
