//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKÜTÜPHANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hareket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Hareket()
        {
            this.Tbl_Ceza = new HashSet<Tbl_Ceza>();
        }
    
        public int HareketID { get; set; }
        public Nullable<int> AlınanKitap { get; set; }
        public Nullable<int> AlanÜye { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<System.DateTime> AlışTarihi { get; set; }
        public Nullable<System.DateTime> İadeTarihi { get; set; }
        public Nullable<System.DateTime> ÜyeİadeTarihi { get; set; }
        public Nullable<bool> İşlemDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ceza> Tbl_Ceza { get; set; }
        public virtual Tbl_Kitap Tbl_Kitap { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
        public virtual Tbl_Üye Tbl_Üye { get; set; }
    }
}
