//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKÜTÜPHANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kitap()
        {
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int KitapID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORİ { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public string BASIMYILI { get; set; }
        public string YAYINEVİ { get; set; }
        public string SAYFA { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string KitapFoto { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual Tbl_Yazar Tbl_Yazar { get; set; }
    }
}
