//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKÜTÜPHANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Üye
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Üye()
        {
            this.Tbl_Ceza = new HashSet<Tbl_Ceza>();
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int ÜyeID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string MAİL { get; set; }
        public string KULLANICIADI { get; set; }
        public string ŞİFRE { get; set; }
        public string FOTOĞRAF { get; set; }
        public string TELEFON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Ceza> Tbl_Ceza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
    }
}
